name: Fix terraform file formatting

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform fmr
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: false