on:
    workflow_dispatch:
      inputs:
        es:
          type: boolean
          default: false
          description: Use Repo 1?
        dr:
          type: boolean
          default: false
          description: Use Repo 2?
jobs:
    es-job:
      name: Repo 1 Job
      runs-on: ubuntu-latest
      if: github.event.inputs.es == 'true'
      steps:
        - run: echo "some repo 1 job"
    
    dr-job:
      name: Repo 2 Job
      runs-on: ubuntu-latest
      if: github.event.inputs.dr == 'true'
      steps:
        - run: echo "some repo 2 job"