on:
  workflow_dispatch:
    inputs:
      es:
        type: boolean
        default: false
        description: Use Repo 1?
      dr:
        type: boolean
        default: false
        description: Use Repo 2?
      environment:
        description: 'Define env name dev or live'      
        required: true  
env: 
  ENV: ${{ github.event.inputs.environment }}
    
jobs:
      common-job:
        name: Repo 1 Job
        runs-on: ubuntu-latest
        steps:
          - run: echo 'This is commmon job'

      es-job:
        name: Repo 1 Job
        runs-on: ubuntu-latest
        needs: common-job
        if: github.event.inputs.es == 'true'
        steps:
          - run: echo ${{ env.ENV }}

  
      dr-job:
        name: Repo 2 Job
        runs-on: ubuntu-latest
        needs: common-job
        if: github.event.inputs.dr == 'true'
        steps:
          - run: echo "some repo 2 job"